# Generated by Django 2.1.2 on 2019-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='re_publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rule', models.CharField(default='', max_length=100)),
                ('src_strm', models.CharField(default='', max_length=100)),
                ('re_start', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='server_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(default='', max_length=100)),
                ('name_server', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_stream', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('bandwidth', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('input', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
