# Generated by Django 2.1.2 on 2019-01-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmspanelapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='re_publish',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
