# Generated by Django 2.1.2 on 2019-01-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmspanelapi', '0002_re_publish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
