# Generated by Django 2.1.2 on 2018-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panelapi', '0008_auto_20181203_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(default='', max_length=100)),
                ('name_server', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
    ]
