# Generated by Django 2.1.2 on 2018-12-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_panelapi', '0009_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_id',
            name='name_server',
        ),
    ]
