# Generated by Django 2.1.2 on 2018-12-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panelapi', '0010_remove_server_id_name_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='re_publish',
            name='re_start',
            field=models.CharField(default='', max_length=100),
        ),
    ]
