# Generated by Django 2.1.2 on 2018-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panelapi', '0011_re_publish_re_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='re_publish',
            name='re_start',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
