# Generated by Django 2.1.2 on 2018-11-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vega1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name_server',
            field=models.CharField(default='', max_length=100),
        ),
    ]
