# Generated by Django 2.1.2 on 2018-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vega1', '0002_server_name_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('bandwidth', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('input', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
