# Generated by Django 2.1.2 on 2018-11-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vega1', '0003_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='id1',
        ),
    ]
