# Generated by Django 2.1.2 on 2018-12-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vega1', '0007_auto_20181203_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'server', 'verbose_name_plural': 'servers'},
        ),
    ]
